spring:
  profiles:
    active: local  # ?? prod, dev ?? ??

---

spring:
  config:
    activate:
      on-profile: local

    servlet:
      multipart:
        location: /home/t25123/v0.5src/mobile/App_Back/uploads/tmp

  datasource:
    url: jdbc:mariadb://localhost:3306/db25123
    driver-class-name: org.mariadb.jdbc.Driver
    username: dbid251
    password: dbpass251

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MariaDBDialect
    open-in-view: false

  logging:
    level:
      org.hibernate.SQL: debug

server:
  port: 60023

jwt:
  secret: N1y!$7uG9!zL@Xk9^+hYtP%29&R$8pWv3
  expirationMs: 3600000  # 1시간 (1000ms * 60s * 60min)

# Swagger
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
